name: backend

on:
  push:
    branches: [ sem_07 ]
  pull_request:
    branches: [ sem_07 ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checking-out repository
        uses: actions/checkout@v2
      
      - name: Install dependecies
        run: |
          sudo apt install libgtest-dev
          sudo apt-get -y install google-mock
              
      - name: Unit testing
        run: |
          cd sem_07/WEB/labs/back
          mkdir build
          cd build
          cmake .. -DWITH_TESTS=1
          make
          
          echo "Testing business logic..."
          ./lib/business_logic/tests/test_business
          echo "Testing data access layer..."
          ./lib/data_access_layer/tests/test_data
