name: backend

on:
  push:
    branches: [ sem_07 ]
  pull_request:
    branches: [ sem_07 ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        
        env:
          POSTGRES_PASSWORD: postgres
          
        ports:
          - 5432:5432
          
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checking-out repository
        uses: actions/checkout@v2
      
      - name: Install dependecies
        run: |
          sudo apt -y update
          sudo apt -y install libgtest-dev
          sudo apt -y install libgmock-dev
          sudo apt -y install postgresql postgresql-contrib
      
      - name: Build tests
        working-directory: sem_07/WEB/labs/back
        run: |
          mkdir build
          cd build
          cmake .. -DWITH_TESTS=1
          make
          
      - name: Unit testing business_logic
        working-directory: sem_07/WEB/labs/back/build
        run: |
          ./lib/business_logic/tests/test_business
          
      - name: Unit testing data_access_layer
        working-directory: sem_07/WEB/labs/back/build
        run: |
          ./lib/data_access_layer/tests/test_data
      
      - name: Create database
        working-directory: sem_07/WEB/labs/back/lib/data_access_layer/src/sql_script
        run: |
          psql "user=postgres password=postgres port=5432 hostaddr=127.0.0.1" -c "CREATE DATABASE software"
          psql "user=postgres password=postgres port=5432 hostaddr=127.0.0.1 dbname=software" < table.sql
          psql "user=postgres password=postgres port=5432 hostaddr=127.0.0.1 dbname=software" < constraint.sql
      
      - name: Intgration testing business_logic
        working-directory: sem_07/WEB/labs/back/build
        run: |
          ./lib/business_logic/tests/int_test_business
     
      - name: Intgration testing data_access_layer
        working-directory: sem_07/WEB/labs/back/build
        run: |
          ./lib/data_access_layer/tests/int_test_data
      